FROM ubuntu:latest

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y python3 python3-pip


COPY requirements.txt ./

RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8001

# CMD ["python3", "manage.py", "runserver", "0.0.0.0:8001"]
CMD ["gunicorn", "--bind", "0.0.0.0:8001", "python_executor.wsgi:application"]