FROM ubuntu:latest

WORKDIR /usr/src/app

RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    apt-get install -y nodejs 

COPY requirements.txt ./

RUN pip3 install -r requirements.txt

COPY . .

EXPOSE 8002

# CMD ["python3", "manage.py", "runserver", "0.0.0.0:8002"]
CMD ["gunicorn","--workers=3", "--bind", "0.0.0.0:8002", "python_executor.wsgi:application"]